language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t luizgomaciel/docker-react -f Dockerfile.dev .

script:
  - docker run luizgomaciel/docker-react npm run test -- --coverage

