sudo: required
language: node_js
node_js:
  - 6

services:
  - docker

before_install:
  - docker build -t luizgomaciel/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true luizgomaciel/docker-react npm run test -- --coverage

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: docker-react-heroku-brazil