sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t luizgomaciel/docker-react -f Dockerfile .

script:
  - docker run -e CI=true luizgomaciel/docker-react npm run test -- --coverage

deploy:
  provider: heroku:git
  api_key: $HEROKU_API_KEY
  edge: true 
  app: docker-react-heroku-brazil

