sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t luizgomaciel/docker-react -f Dockerfile .

script:
  - docker run -e luizgomaciel/docker-react npm run test -- --coverage

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: docker-react-heroku-brazil
