sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t luizgomaciel/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true luizgomaciel/docker-react npm run test -- --coverage

deploy:
  provider: heroku
  api_key:
    secure: "HEROKU_SECRET_KEY"
  app: docker-react-heroku-brazil
  on:
    branch: master
