sudo: required
language: node_js
node_js:
  - 10

services:
  - docker

before_install:
  - docker build -t luizgomaciel/docker-react -f Dockerfile.dev .



deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: docker-react-heroku-brazil